//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for e_countryCode_deprecated.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="e_countryCode_deprecated">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OpenDRIVE"/>
 *     &lt;enumeration value="Austria"/>
 *     &lt;enumeration value="Brazil"/>
 *     &lt;enumeration value="China"/>
 *     &lt;enumeration value="France"/>
 *     &lt;enumeration value="Germany"/>
 *     &lt;enumeration value="Italy"/>
 *     &lt;enumeration value="Switzerland"/>
 *     &lt;enumeration value="USA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "e_countryCode_deprecated")
@XmlEnum
public enum ECountryCodeDeprecated {

    @XmlEnumValue("OpenDRIVE")
    OPEN_DRIVE("OpenDRIVE"),
    @XmlEnumValue("Austria")
    AUSTRIA("Austria"),
    @XmlEnumValue("Brazil")
    BRAZIL("Brazil"),
    @XmlEnumValue("China")
    CHINA("China"),
    @XmlEnumValue("France")
    FRANCE("France"),
    @XmlEnumValue("Germany")
    GERMANY("Germany"),
    @XmlEnumValue("Italy")
    ITALY("Italy"),
    @XmlEnumValue("Switzerland")
    SWITZERLAND("Switzerland"),
    USA("USA");
    private final String value;

    ECountryCodeDeprecated(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ECountryCodeDeprecated fromValue(String v) {
        for (ECountryCodeDeprecated c: ECountryCodeDeprecated.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
