//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for e_road_surface_CRG_mode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="e_road_surface_CRG_mode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="attached"/>
 *     &lt;enumeration value="attached0"/>
 *     &lt;enumeration value="genuine"/>
 *     &lt;enumeration value="global"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "e_road_surface_CRG_mode")
@XmlEnum
public enum ERoadSurfaceCRGMode {

    @XmlEnumValue("attached")
    ATTACHED("attached"),
    @XmlEnumValue("attached0")
    ATTACHED_0("attached0"),
    @XmlEnumValue("genuine")
    GENUINE("genuine"),
    @XmlEnumValue("global")
    GLOBAL("global");
    private final String value;

    ERoadSurfaceCRGMode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ERoadSurfaceCRGMode fromValue(String v) {
        for (ERoadSurfaceCRGMode c: ERoadSurfaceCRGMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
