//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for e_road_lanes_laneSection_lcr_lane_roadMark_laneChange.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="e_road_lanes_laneSection_lcr_lane_roadMark_laneChange">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="increase"/>
 *     &lt;enumeration value="decrease"/>
 *     &lt;enumeration value="both"/>
 *     &lt;enumeration value="none"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "e_road_lanes_laneSection_lcr_lane_roadMark_laneChange")
@XmlEnum
public enum ERoadLanesLaneSectionLcrLaneRoadMarkLaneChange {

    @XmlEnumValue("increase")
    INCREASE("increase"),
    @XmlEnumValue("decrease")
    DECREASE("decrease"),
    @XmlEnumValue("both")
    BOTH("both"),
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    ERoadLanesLaneSectionLcrLaneRoadMarkLaneChange(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ERoadLanesLaneSectionLcrLaneRoadMarkLaneChange fromValue(String v) {
        for (ERoadLanesLaneSectionLcrLaneRoadMarkLaneChange c: ERoadLanesLaneSectionLcrLaneRoadMarkLaneChange.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
