//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for e_roadMarkRule.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="e_roadMarkRule">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="no passing"/>
 *     &lt;enumeration value="caution"/>
 *     &lt;enumeration value="none"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "e_roadMarkRule")
@XmlEnum
public enum ERoadMarkRule {

    @XmlEnumValue("no passing")
    NO_PASSING("no passing"),
    @XmlEnumValue("caution")
    CAUTION("caution"),
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    ERoadMarkRule(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ERoadMarkRule fromValue(String v) {
        for (ERoadMarkRule c: ERoadMarkRule.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
