//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for e_roadType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="e_roadType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="rural"/>
 *     &lt;enumeration value="motorway"/>
 *     &lt;enumeration value="town"/>
 *     &lt;enumeration value="lowSpeed"/>
 *     &lt;enumeration value="pedestrian"/>
 *     &lt;enumeration value="bicycle"/>
 *     &lt;enumeration value="townExpressway"/>
 *     &lt;enumeration value="townCollector"/>
 *     &lt;enumeration value="townArterial"/>
 *     &lt;enumeration value="townPrivate"/>
 *     &lt;enumeration value="townLocal"/>
 *     &lt;enumeration value="townPlayStreet"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "e_roadType")
@XmlEnum
public enum ERoadType {

    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),
    @XmlEnumValue("rural")
    RURAL("rural"),
    @XmlEnumValue("motorway")
    MOTORWAY("motorway"),
    @XmlEnumValue("town")
    TOWN("town"),
    @XmlEnumValue("lowSpeed")
    LOW_SPEED("lowSpeed"),
    @XmlEnumValue("pedestrian")
    PEDESTRIAN("pedestrian"),
    @XmlEnumValue("bicycle")
    BICYCLE("bicycle"),
    @XmlEnumValue("townExpressway")
    TOWN_EXPRESSWAY("townExpressway"),
    @XmlEnumValue("townCollector")
    TOWN_COLLECTOR("townCollector"),
    @XmlEnumValue("townArterial")
    TOWN_ARTERIAL("townArterial"),
    @XmlEnumValue("townPrivate")
    TOWN_PRIVATE("townPrivate"),
    @XmlEnumValue("townLocal")
    TOWN_LOCAL("townLocal"),
    @XmlEnumValue("townPlayStreet")
    TOWN_PLAY_STREET("townPlayStreet");
    private final String value;

    ERoadType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ERoadType fromValue(String v) {
        for (ERoadType c: ERoadType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
