//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for e_unitDistance.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="e_unitDistance">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="m"/>
 *     &lt;enumeration value="km"/>
 *     &lt;enumeration value="ft"/>
 *     &lt;enumeration value="mile"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "e_unitDistance")
@XmlEnum
public enum EUnitDistance {

    @XmlEnumValue("m")
    M("m"),
    @XmlEnumValue("km")
    KM("km"),
    @XmlEnumValue("ft")
    FT("ft"),
    @XmlEnumValue("mile")
    MILE("mile");
    private final String value;

    EUnitDistance(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EUnitDistance fromValue(String v) {
        for (EUnitDistance c: EUnitDistance.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
