//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for e_unitSpeed.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="e_unitSpeed">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="m/s"/>
 *     &lt;enumeration value="mph"/>
 *     &lt;enumeration value="km/h"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "e_unitSpeed")
@XmlEnum
public enum EUnitSpeed {

    @XmlEnumValue("m/s")
    M_S("m/s"),
    @XmlEnumValue("mph")
    MPH("mph"),
    @XmlEnumValue("km/h")
    KM_H("km/h");
    private final String value;

    EUnitSpeed(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EUnitSpeed fromValue(String v) {
        for (EUnitSpeed c: EUnitSpeed.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
