//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_dataQuality_Error complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_dataQuality_Error">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="xyAbsolute" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="zAbsolute" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="xyRelative" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="zRelative" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_dataQuality_Error")
public class TDataQualityError {

    @XmlAttribute(name = "xyAbsolute", required = true)
    protected double xyAbsolute;
    @XmlAttribute(name = "zAbsolute", required = true)
    protected double zAbsolute;
    @XmlAttribute(name = "xyRelative", required = true)
    protected double xyRelative;
    @XmlAttribute(name = "zRelative", required = true)
    protected double zRelative;

    /**
     * Gets the value of the xyAbsolute property.
     * 
     */
    public double getXyAbsolute() {
        return xyAbsolute;
    }

    /**
     * Sets the value of the xyAbsolute property.
     * 
     */
    public void setXyAbsolute(double value) {
        this.xyAbsolute = value;
    }

    /**
     * Gets the value of the zAbsolute property.
     * 
     */
    public double getZAbsolute() {
        return zAbsolute;
    }

    /**
     * Sets the value of the zAbsolute property.
     * 
     */
    public void setZAbsolute(double value) {
        this.zAbsolute = value;
    }

    /**
     * Gets the value of the xyRelative property.
     * 
     */
    public double getXyRelative() {
        return xyRelative;
    }

    /**
     * Sets the value of the xyRelative property.
     * 
     */
    public void setXyRelative(double value) {
        this.xyRelative = value;
    }

    /**
     * Gets the value of the zRelative property.
     * 
     */
    public double getZRelative() {
        return zRelative;
    }

    /**
     * Sets the value of the zRelative property.
     * 
     */
    public void setZRelative(double value) {
        this.zRelative = value;
    }

}
