//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_junction_connection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_junction_connection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="predecessor" type="{}t_junction_predecessorSuccessor" minOccurs="0"/>
 *         &lt;element name="successor" type="{}t_junction_predecessorSuccessor" minOccurs="0"/>
 *         &lt;element name="laneLink" type="{}t_junction_connection_laneLink" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{}g_additionalData"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="incomingRoad" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="connectingRoad" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contactPoint" use="required" type="{}e_contactPoint" />
 *       &lt;attribute name="connectionMaster" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{}e_junction_type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_junction_connection", propOrder = {
    "predecessor",
    "successor",
    "laneLink",
    "userData",
    "include",
    "dataQuality"
})
public class TJunctionConnection {

    protected TJunctionPredecessorSuccessor predecessor;
    protected TJunctionPredecessorSuccessor successor;
    protected List<TJunctionConnectionLaneLink> laneLink;
    protected List<TUserData> userData;
    protected List<TInclude> include;
    protected TDataQuality dataQuality;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "incomingRoad", required = true)
    protected String incomingRoad;
    @XmlAttribute(name = "connectingRoad", required = true)
    protected String connectingRoad;
    @XmlAttribute(name = "contactPoint", required = true)
    protected EContactPoint contactPoint;
    @XmlAttribute(name = "connectionMaster")
    protected String connectionMaster;
    @XmlAttribute(name = "type")
    protected EJunctionType type;

    /**
     * Gets the value of the predecessor property.
     * 
     * @return
     *     possible object is
     *     {@link TJunctionPredecessorSuccessor }
     *     
     */
    public TJunctionPredecessorSuccessor getPredecessor() {
        return predecessor;
    }

    /**
     * Sets the value of the predecessor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TJunctionPredecessorSuccessor }
     *     
     */
    public void setPredecessor(TJunctionPredecessorSuccessor value) {
        this.predecessor = value;
    }

    /**
     * Gets the value of the successor property.
     * 
     * @return
     *     possible object is
     *     {@link TJunctionPredecessorSuccessor }
     *     
     */
    public TJunctionPredecessorSuccessor getSuccessor() {
        return successor;
    }

    /**
     * Sets the value of the successor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TJunctionPredecessorSuccessor }
     *     
     */
    public void setSuccessor(TJunctionPredecessorSuccessor value) {
        this.successor = value;
    }

    /**
     * Gets the value of the laneLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the laneLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLaneLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TJunctionConnectionLaneLink }
     * 
     * 
     */
    public List<TJunctionConnectionLaneLink> getLaneLink() {
        if (laneLink == null) {
            laneLink = new ArrayList<TJunctionConnectionLaneLink>();
        }
        return this.laneLink;
    }

    /**
     * Gets the value of the userData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TUserData }
     * 
     * 
     */
    public List<TUserData> getUserData() {
        if (userData == null) {
            userData = new ArrayList<TUserData>();
        }
        return this.userData;
    }

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInclude }
     * 
     * 
     */
    public List<TInclude> getInclude() {
        if (include == null) {
            include = new ArrayList<TInclude>();
        }
        return this.include;
    }

    /**
     * Gets the value of the dataQuality property.
     * 
     * @return
     *     possible object is
     *     {@link TDataQuality }
     *     
     */
    public TDataQuality getDataQuality() {
        return dataQuality;
    }

    /**
     * Sets the value of the dataQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataQuality }
     *     
     */
    public void setDataQuality(TDataQuality value) {
        this.dataQuality = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the incomingRoad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomingRoad() {
        return incomingRoad;
    }

    /**
     * Sets the value of the incomingRoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomingRoad(String value) {
        this.incomingRoad = value;
    }

    /**
     * Gets the value of the connectingRoad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectingRoad() {
        return connectingRoad;
    }

    /**
     * Sets the value of the connectingRoad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectingRoad(String value) {
        this.connectingRoad = value;
    }

    /**
     * Gets the value of the contactPoint property.
     * 
     * @return
     *     possible object is
     *     {@link EContactPoint }
     *     
     */
    public EContactPoint getContactPoint() {
        return contactPoint;
    }

    /**
     * Sets the value of the contactPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link EContactPoint }
     *     
     */
    public void setContactPoint(EContactPoint value) {
        this.contactPoint = value;
    }

    /**
     * Gets the value of the connectionMaster property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionMaster() {
        return connectionMaster;
    }

    /**
     * Sets the value of the connectionMaster property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionMaster(String value) {
        this.connectionMaster = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EJunctionType }
     *     
     */
    public EJunctionType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EJunctionType }
     *     
     */
    public void setType(EJunctionType value) {
        this.type = value;
    }

}
