//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_road complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_road">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="link" type="{}t_road_link" minOccurs="0"/>
 *         &lt;element name="type" type="{}t_road_type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="planView" type="{}t_road_planView"/>
 *         &lt;element name="elevationProfile" type="{}t_road_elevationProfile" minOccurs="0"/>
 *         &lt;element name="lateralProfile" type="{}t_road_lateralProfile" minOccurs="0"/>
 *         &lt;element name="lanes" type="{}t_road_lanes"/>
 *         &lt;element name="objects" type="{}t_road_objects" minOccurs="0"/>
 *         &lt;element name="signals" type="{}t_road_signals" minOccurs="0"/>
 *         &lt;element name="surface" type="{}t_road_surface" minOccurs="0"/>
 *         &lt;element name="railroad" type="{}t_road_railroad" minOccurs="0"/>
 *         &lt;group ref="{}g_additionalData"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="length" use="required" type="{}t_grEqZero" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="junction" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rule" type="{}e_trafficRule" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_road", propOrder = {
    "link",
    "type",
    "planView",
    "elevationProfile",
    "lateralProfile",
    "lanes",
    "objects",
    "signals",
    "surface",
    "railroad",
    "userData",
    "include",
    "dataQuality"
})
public class TRoad {

    protected TRoadLink link;
    protected List<TRoadType> type;
    @XmlElement(required = true)
    protected TRoadPlanView planView;
    protected TRoadElevationProfile elevationProfile;
    protected TRoadLateralProfile lateralProfile;
    @XmlElement(required = true)
    protected TRoadLanes lanes;
    protected TRoadObjects objects;
    protected TRoadSignals signals;
    protected TRoadSurface surface;
    protected TRoadRailroad railroad;
    protected List<TUserData> userData;
    protected List<TInclude> include;
    protected TDataQuality dataQuality;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "length", required = true)
    protected double length;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "junction", required = true)
    protected String junction;
    @XmlAttribute(name = "rule")
    protected ETrafficRule rule;

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link TRoadLink }
     *     
     */
    public TRoadLink getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRoadLink }
     *     
     */
    public void setLink(TRoadLink value) {
        this.link = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadType }
     * 
     * 
     */
    public List<TRoadType> getType() {
        if (type == null) {
            type = new ArrayList<TRoadType>();
        }
        return this.type;
    }

    /**
     * Gets the value of the planView property.
     * 
     * @return
     *     possible object is
     *     {@link TRoadPlanView }
     *     
     */
    public TRoadPlanView getPlanView() {
        return planView;
    }

    /**
     * Sets the value of the planView property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRoadPlanView }
     *     
     */
    public void setPlanView(TRoadPlanView value) {
        this.planView = value;
    }

    /**
     * Gets the value of the elevationProfile property.
     * 
     * @return
     *     possible object is
     *     {@link TRoadElevationProfile }
     *     
     */
    public TRoadElevationProfile getElevationProfile() {
        return elevationProfile;
    }

    /**
     * Sets the value of the elevationProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRoadElevationProfile }
     *     
     */
    public void setElevationProfile(TRoadElevationProfile value) {
        this.elevationProfile = value;
    }

    /**
     * Gets the value of the lateralProfile property.
     * 
     * @return
     *     possible object is
     *     {@link TRoadLateralProfile }
     *     
     */
    public TRoadLateralProfile getLateralProfile() {
        return lateralProfile;
    }

    /**
     * Sets the value of the lateralProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRoadLateralProfile }
     *     
     */
    public void setLateralProfile(TRoadLateralProfile value) {
        this.lateralProfile = value;
    }

    /**
     * Gets the value of the lanes property.
     * 
     * @return
     *     possible object is
     *     {@link TRoadLanes }
     *     
     */
    public TRoadLanes getLanes() {
        return lanes;
    }

    /**
     * Sets the value of the lanes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRoadLanes }
     *     
     */
    public void setLanes(TRoadLanes value) {
        this.lanes = value;
    }

    /**
     * Gets the value of the objects property.
     * 
     * @return
     *     possible object is
     *     {@link TRoadObjects }
     *     
     */
    public TRoadObjects getObjects() {
        return objects;
    }

    /**
     * Sets the value of the objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRoadObjects }
     *     
     */
    public void setObjects(TRoadObjects value) {
        this.objects = value;
    }

    /**
     * Gets the value of the signals property.
     * 
     * @return
     *     possible object is
     *     {@link TRoadSignals }
     *     
     */
    public TRoadSignals getSignals() {
        return signals;
    }

    /**
     * Sets the value of the signals property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRoadSignals }
     *     
     */
    public void setSignals(TRoadSignals value) {
        this.signals = value;
    }

    /**
     * Gets the value of the surface property.
     * 
     * @return
     *     possible object is
     *     {@link TRoadSurface }
     *     
     */
    public TRoadSurface getSurface() {
        return surface;
    }

    /**
     * Sets the value of the surface property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRoadSurface }
     *     
     */
    public void setSurface(TRoadSurface value) {
        this.surface = value;
    }

    /**
     * Gets the value of the railroad property.
     * 
     * @return
     *     possible object is
     *     {@link TRoadRailroad }
     *     
     */
    public TRoadRailroad getRailroad() {
        return railroad;
    }

    /**
     * Sets the value of the railroad property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRoadRailroad }
     *     
     */
    public void setRailroad(TRoadRailroad value) {
        this.railroad = value;
    }

    /**
     * Gets the value of the userData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TUserData }
     * 
     * 
     */
    public List<TUserData> getUserData() {
        if (userData == null) {
            userData = new ArrayList<TUserData>();
        }
        return this.userData;
    }

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInclude }
     * 
     * 
     */
    public List<TInclude> getInclude() {
        if (include == null) {
            include = new ArrayList<TInclude>();
        }
        return this.include;
    }

    /**
     * Gets the value of the dataQuality property.
     * 
     * @return
     *     possible object is
     *     {@link TDataQuality }
     *     
     */
    public TDataQuality getDataQuality() {
        return dataQuality;
    }

    /**
     * Sets the value of the dataQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataQuality }
     *     
     */
    public void setDataQuality(TDataQuality value) {
        this.dataQuality = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the length property.
     * 
     */
    public double getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     */
    public void setLength(double value) {
        this.length = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the junction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJunction() {
        return junction;
    }

    /**
     * Sets the value of the junction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJunction(String value) {
        this.junction = value;
    }

    /**
     * Gets the value of the rule property.
     * 
     * @return
     *     possible object is
     *     {@link ETrafficRule }
     *     
     */
    public ETrafficRule getRule() {
        return rule;
    }

    /**
     * Sets the value of the rule property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETrafficRule }
     *     
     */
    public void setRule(ETrafficRule value) {
        this.rule = value;
    }

}
