//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_road_objects_object_markings_marking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_road_objects_object_markings_marking">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cornerReference" type="{}t_road_objects_object_markings_marking_cornerReference" maxOccurs="unbounded" minOccurs="2"/>
 *         &lt;group ref="{}g_additionalData"/>
 *       &lt;/sequence>
 *       &lt;attribute name="side" use="required" type="{}e_sideType" />
 *       &lt;attribute name="weight" use="required" type="{}e_roadMarkWeight" />
 *       &lt;attribute name="width" type="{}t_grEqZero" />
 *       &lt;attribute name="color" use="required" type="{}e_roadMarkColor" />
 *       &lt;attribute name="zOffset" type="{}t_grEqZero" />
 *       &lt;attribute name="spaceLength" use="required" type="{}t_grEqZero" />
 *       &lt;attribute name="lineLength" use="required" type="{}t_grEqZero" />
 *       &lt;attribute name="startOffset" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="stopOffset" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_road_objects_object_markings_marking", propOrder = {
    "cornerReference",
    "userData",
    "include",
    "dataQuality"
})
public class TRoadObjectsObjectMarkingsMarking {

    @XmlElement(required = true)
    protected List<TRoadObjectsObjectMarkingsMarkingCornerReference> cornerReference;
    protected List<TUserData> userData;
    protected List<TInclude> include;
    protected TDataQuality dataQuality;
    @XmlAttribute(name = "side", required = true)
    protected ESideType side;
    @XmlAttribute(name = "weight", required = true)
    protected ERoadMarkWeight weight;
    @XmlAttribute(name = "width")
    protected Double width;
    @XmlAttribute(name = "color", required = true)
    protected ERoadMarkColor color;
    @XmlAttribute(name = "zOffset")
    protected Double zOffset;
    @XmlAttribute(name = "spaceLength", required = true)
    protected double spaceLength;
    @XmlAttribute(name = "lineLength", required = true)
    protected double lineLength;
    @XmlAttribute(name = "startOffset", required = true)
    protected double startOffset;
    @XmlAttribute(name = "stopOffset", required = true)
    protected double stopOffset;

    /**
     * Gets the value of the cornerReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cornerReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCornerReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadObjectsObjectMarkingsMarkingCornerReference }
     * 
     * 
     */
    public List<TRoadObjectsObjectMarkingsMarkingCornerReference> getCornerReference() {
        if (cornerReference == null) {
            cornerReference = new ArrayList<TRoadObjectsObjectMarkingsMarkingCornerReference>();
        }
        return this.cornerReference;
    }

    /**
     * Gets the value of the userData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TUserData }
     * 
     * 
     */
    public List<TUserData> getUserData() {
        if (userData == null) {
            userData = new ArrayList<TUserData>();
        }
        return this.userData;
    }

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInclude }
     * 
     * 
     */
    public List<TInclude> getInclude() {
        if (include == null) {
            include = new ArrayList<TInclude>();
        }
        return this.include;
    }

    /**
     * Gets the value of the dataQuality property.
     * 
     * @return
     *     possible object is
     *     {@link TDataQuality }
     *     
     */
    public TDataQuality getDataQuality() {
        return dataQuality;
    }

    /**
     * Sets the value of the dataQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataQuality }
     *     
     */
    public void setDataQuality(TDataQuality value) {
        this.dataQuality = value;
    }

    /**
     * Gets the value of the side property.
     * 
     * @return
     *     possible object is
     *     {@link ESideType }
     *     
     */
    public ESideType getSide() {
        return side;
    }

    /**
     * Sets the value of the side property.
     * 
     * @param value
     *     allowed object is
     *     {@link ESideType }
     *     
     */
    public void setSide(ESideType value) {
        this.side = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link ERoadMarkWeight }
     *     
     */
    public ERoadMarkWeight getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link ERoadMarkWeight }
     *     
     */
    public void setWeight(ERoadMarkWeight value) {
        this.weight = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWidth(Double value) {
        this.width = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link ERoadMarkColor }
     *     
     */
    public ERoadMarkColor getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link ERoadMarkColor }
     *     
     */
    public void setColor(ERoadMarkColor value) {
        this.color = value;
    }

    /**
     * Gets the value of the zOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getZOffset() {
        return zOffset;
    }

    /**
     * Sets the value of the zOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setZOffset(Double value) {
        this.zOffset = value;
    }

    /**
     * Gets the value of the spaceLength property.
     * 
     */
    public double getSpaceLength() {
        return spaceLength;
    }

    /**
     * Sets the value of the spaceLength property.
     * 
     */
    public void setSpaceLength(double value) {
        this.spaceLength = value;
    }

    /**
     * Gets the value of the lineLength property.
     * 
     */
    public double getLineLength() {
        return lineLength;
    }

    /**
     * Sets the value of the lineLength property.
     * 
     */
    public void setLineLength(double value) {
        this.lineLength = value;
    }

    /**
     * Gets the value of the startOffset property.
     * 
     */
    public double getStartOffset() {
        return startOffset;
    }

    /**
     * Sets the value of the startOffset property.
     * 
     */
    public void setStartOffset(double value) {
        this.startOffset = value;
    }

    /**
     * Gets the value of the stopOffset property.
     * 
     */
    public double getStopOffset() {
        return stopOffset;
    }

    /**
     * Sets the value of the stopOffset property.
     * 
     */
    public void setStopOffset(double value) {
        this.stopOffset = value;
    }

}
