//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_road_objects_object_outlines_outline complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_road_objects_object_outlines_outline">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cornerRoad" type="{}t_road_objects_object_outlines_outline_cornerRoad" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="cornerLocal" type="{}t_road_objects_object_outlines_outline_cornerLocal" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{}g_additionalData"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="fillType" use="required" type="{}e_outlineFillType" />
 *       &lt;attribute name="outer" use="required" type="{}t_bool" />
 *       &lt;attribute name="closed" use="required" type="{}t_bool" />
 *       &lt;attribute name="laneType" use="required" type="{}e_laneType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_road_objects_object_outlines_outline", propOrder = {
    "cornerRoad",
    "cornerLocal",
    "userData",
    "include",
    "dataQuality"
})
public class TRoadObjectsObjectOutlinesOutline {

    protected List<TRoadObjectsObjectOutlinesOutlineCornerRoad> cornerRoad;
    protected List<TRoadObjectsObjectOutlinesOutlineCornerLocal> cornerLocal;
    protected List<TUserData> userData;
    protected List<TInclude> include;
    protected TDataQuality dataQuality;
    @XmlAttribute(name = "id", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger id;
    @XmlAttribute(name = "fillType", required = true)
    protected EOutlineFillType fillType;
    @XmlAttribute(name = "outer", required = true)
    protected TBool outer;
    @XmlAttribute(name = "closed", required = true)
    protected TBool closed;
    @XmlAttribute(name = "laneType", required = true)
    protected ELaneType laneType;

    /**
     * Gets the value of the cornerRoad property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cornerRoad property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCornerRoad().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadObjectsObjectOutlinesOutlineCornerRoad }
     * 
     * 
     */
    public List<TRoadObjectsObjectOutlinesOutlineCornerRoad> getCornerRoad() {
        if (cornerRoad == null) {
            cornerRoad = new ArrayList<TRoadObjectsObjectOutlinesOutlineCornerRoad>();
        }
        return this.cornerRoad;
    }

    /**
     * Gets the value of the cornerLocal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cornerLocal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCornerLocal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadObjectsObjectOutlinesOutlineCornerLocal }
     * 
     * 
     */
    public List<TRoadObjectsObjectOutlinesOutlineCornerLocal> getCornerLocal() {
        if (cornerLocal == null) {
            cornerLocal = new ArrayList<TRoadObjectsObjectOutlinesOutlineCornerLocal>();
        }
        return this.cornerLocal;
    }

    /**
     * Gets the value of the userData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TUserData }
     * 
     * 
     */
    public List<TUserData> getUserData() {
        if (userData == null) {
            userData = new ArrayList<TUserData>();
        }
        return this.userData;
    }

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInclude }
     * 
     * 
     */
    public List<TInclude> getInclude() {
        if (include == null) {
            include = new ArrayList<TInclude>();
        }
        return this.include;
    }

    /**
     * Gets the value of the dataQuality property.
     * 
     * @return
     *     possible object is
     *     {@link TDataQuality }
     *     
     */
    public TDataQuality getDataQuality() {
        return dataQuality;
    }

    /**
     * Sets the value of the dataQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataQuality }
     *     
     */
    public void setDataQuality(TDataQuality value) {
        this.dataQuality = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the fillType property.
     * 
     * @return
     *     possible object is
     *     {@link EOutlineFillType }
     *     
     */
    public EOutlineFillType getFillType() {
        return fillType;
    }

    /**
     * Sets the value of the fillType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EOutlineFillType }
     *     
     */
    public void setFillType(EOutlineFillType value) {
        this.fillType = value;
    }

    /**
     * Gets the value of the outer property.
     * 
     * @return
     *     possible object is
     *     {@link TBool }
     *     
     */
    public TBool getOuter() {
        return outer;
    }

    /**
     * Sets the value of the outer property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBool }
     *     
     */
    public void setOuter(TBool value) {
        this.outer = value;
    }

    /**
     * Gets the value of the closed property.
     * 
     * @return
     *     possible object is
     *     {@link TBool }
     *     
     */
    public TBool getClosed() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBool }
     *     
     */
    public void setClosed(TBool value) {
        this.closed = value;
    }

    /**
     * Gets the value of the laneType property.
     * 
     * @return
     *     possible object is
     *     {@link ELaneType }
     *     
     */
    public ELaneType getLaneType() {
        return laneType;
    }

    /**
     * Sets the value of the laneType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELaneType }
     *     
     */
    public void setLaneType(ELaneType value) {
        this.laneType = value;
    }

}
