//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_road_surface_CRG complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_road_surface_CRG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{}g_additionalData"/>
 *       &lt;attribute name="file" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sStart" use="required" type="{}t_grEqZero" />
 *       &lt;attribute name="sEnd" use="required" type="{}t_grEqZero" />
 *       &lt;attribute name="orientation" use="required" type="{}e_direction" />
 *       &lt;attribute name="mode" use="required" type="{}e_road_surface_CRG_mode" />
 *       &lt;attribute name="purpose" type="{}e_road_surface_CRG_purpose" />
 *       &lt;attribute name="sOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="tOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="zOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="zScale" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="hOffset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_road_surface_CRG", propOrder = {
    "userData",
    "include",
    "dataQuality"
})
public class TRoadSurfaceCRG {

    protected List<TUserData> userData;
    protected List<TInclude> include;
    protected TDataQuality dataQuality;
    @XmlAttribute(name = "file", required = true)
    protected String file;
    @XmlAttribute(name = "sStart", required = true)
    protected double sStart;
    @XmlAttribute(name = "sEnd", required = true)
    protected double sEnd;
    @XmlAttribute(name = "orientation", required = true)
    protected EDirection orientation;
    @XmlAttribute(name = "mode", required = true)
    protected ERoadSurfaceCRGMode mode;
    @XmlAttribute(name = "purpose")
    protected ERoadSurfaceCRGPurpose purpose;
    @XmlAttribute(name = "sOffset")
    protected Double sOffset;
    @XmlAttribute(name = "tOffset")
    protected Double tOffset;
    @XmlAttribute(name = "zOffset")
    protected Double zOffset;
    @XmlAttribute(name = "zScale")
    protected Double zScale;
    @XmlAttribute(name = "hOffset")
    protected Double hOffset;

    /**
     * Gets the value of the userData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TUserData }
     * 
     * 
     */
    public List<TUserData> getUserData() {
        if (userData == null) {
            userData = new ArrayList<TUserData>();
        }
        return this.userData;
    }

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInclude }
     * 
     * 
     */
    public List<TInclude> getInclude() {
        if (include == null) {
            include = new ArrayList<TInclude>();
        }
        return this.include;
    }

    /**
     * Gets the value of the dataQuality property.
     * 
     * @return
     *     possible object is
     *     {@link TDataQuality }
     *     
     */
    public TDataQuality getDataQuality() {
        return dataQuality;
    }

    /**
     * Sets the value of the dataQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataQuality }
     *     
     */
    public void setDataQuality(TDataQuality value) {
        this.dataQuality = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFile(String value) {
        this.file = value;
    }

    /**
     * Gets the value of the sStart property.
     * 
     */
    public double getSStart() {
        return sStart;
    }

    /**
     * Sets the value of the sStart property.
     * 
     */
    public void setSStart(double value) {
        this.sStart = value;
    }

    /**
     * Gets the value of the sEnd property.
     * 
     */
    public double getSEnd() {
        return sEnd;
    }

    /**
     * Sets the value of the sEnd property.
     * 
     */
    public void setSEnd(double value) {
        this.sEnd = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link EDirection }
     *     
     */
    public EDirection getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDirection }
     *     
     */
    public void setOrientation(EDirection value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link ERoadSurfaceCRGMode }
     *     
     */
    public ERoadSurfaceCRGMode getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ERoadSurfaceCRGMode }
     *     
     */
    public void setMode(ERoadSurfaceCRGMode value) {
        this.mode = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link ERoadSurfaceCRGPurpose }
     *     
     */
    public ERoadSurfaceCRGPurpose getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link ERoadSurfaceCRGPurpose }
     *     
     */
    public void setPurpose(ERoadSurfaceCRGPurpose value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the sOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSOffset() {
        return sOffset;
    }

    /**
     * Sets the value of the sOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSOffset(Double value) {
        this.sOffset = value;
    }

    /**
     * Gets the value of the tOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTOffset() {
        return tOffset;
    }

    /**
     * Sets the value of the tOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTOffset(Double value) {
        this.tOffset = value;
    }

    /**
     * Gets the value of the zOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getZOffset() {
        return zOffset;
    }

    /**
     * Sets the value of the zOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setZOffset(Double value) {
        this.zOffset = value;
    }

    /**
     * Gets the value of the zScale property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getZScale() {
        return zScale;
    }

    /**
     * Sets the value of the zScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setZScale(Double value) {
        this.zScale = value;
    }

    /**
     * Gets the value of the hOffset property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHOffset() {
        return hOffset;
    }

    /**
     * Sets the value of the hOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHOffset(Double value) {
        this.hOffset = value;
    }

}
