//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_road_lanes_laneSection_lr_lane complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_road_lanes_laneSection_lr_lane">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="link" type="{}t_road_lanes_laneSection_lcr_lane_link" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="width" type="{}t_road_lanes_laneSection_lr_lane_width" maxOccurs="unbounded"/>
 *           &lt;element name="border" type="{}t_road_lanes_laneSection_lr_lane_border" maxOccurs="unbounded"/>
 *         &lt;/choice>
 *         &lt;element name="roadMark" type="{}t_road_lanes_laneSection_lcr_lane_roadMark" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="material" type="{}t_road_lanes_laneSection_lr_lane_material" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="visibility" type="{}t_road_lanes_laneSection_lr_lane_visibility" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="speed" type="{}t_road_lanes_laneSection_lr_lane_speed" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="access" type="{}t_road_lanes_laneSection_lr_lane_access" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="height" type="{}t_road_lanes_laneSection_lr_lane_height" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="rule" type="{}t_road_lanes_laneSection_lr_lane_rule" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{}g_additionalData"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{}e_laneType" />
 *       &lt;attribute name="level" type="{}t_bool" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_road_lanes_laneSection_lr_lane", propOrder = {
    "link",
    "widthOrBorder",
    "roadMark",
    "material",
    "visibility",
    "speed",
    "access",
    "height",
    "rule",
    "userData",
    "include",
    "dataQuality"
})
@XmlSeeAlso({
    TRoadLanesLaneSectionRightLane.class,
    TRoadLanesLaneSectionLeftLane.class
})
public class TRoadLanesLaneSectionLrLane {

    protected TRoadLanesLaneSectionLcrLaneLink link;
    @XmlElements({
        @XmlElement(name = "width", type = TRoadLanesLaneSectionLrLaneWidth.class),
        @XmlElement(name = "border", type = TRoadLanesLaneSectionLrLaneBorder.class)
    })
    protected List<Object> widthOrBorder;
    protected List<TRoadLanesLaneSectionLcrLaneRoadMark> roadMark;
    protected List<TRoadLanesLaneSectionLrLaneMaterial> material;
    protected List<TRoadLanesLaneSectionLrLaneVisibility> visibility;
    protected List<TRoadLanesLaneSectionLrLaneSpeed> speed;
    protected List<TRoadLanesLaneSectionLrLaneAccess> access;
    protected List<TRoadLanesLaneSectionLrLaneHeight> height;
    protected List<TRoadLanesLaneSectionLrLaneRule> rule;
    protected List<TUserData> userData;
    protected List<TInclude> include;
    protected TDataQuality dataQuality;
    @XmlAttribute(name = "type", required = true)
    protected ELaneType type;
    @XmlAttribute(name = "level")
    protected TBool level;

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link TRoadLanesLaneSectionLcrLaneLink }
     *     
     */
    public TRoadLanesLaneSectionLcrLaneLink getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRoadLanesLaneSectionLcrLaneLink }
     *     
     */
    public void setLink(TRoadLanesLaneSectionLcrLaneLink value) {
        this.link = value;
    }

    /**
     * Gets the value of the widthOrBorder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the widthOrBorder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWidthOrBorder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadLanesLaneSectionLrLaneWidth }
     * {@link TRoadLanesLaneSectionLrLaneBorder }
     * 
     * 
     */
    public List<Object> getWidthOrBorder() {
        if (widthOrBorder == null) {
            widthOrBorder = new ArrayList<Object>();
        }
        return this.widthOrBorder;
    }

    /**
     * Gets the value of the roadMark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the roadMark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRoadMark().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadLanesLaneSectionLcrLaneRoadMark }
     * 
     * 
     */
    public List<TRoadLanesLaneSectionLcrLaneRoadMark> getRoadMark() {
        if (roadMark == null) {
            roadMark = new ArrayList<TRoadLanesLaneSectionLcrLaneRoadMark>();
        }
        return this.roadMark;
    }

    /**
     * Gets the value of the material property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the material property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMaterial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadLanesLaneSectionLrLaneMaterial }
     * 
     * 
     */
    public List<TRoadLanesLaneSectionLrLaneMaterial> getMaterial() {
        if (material == null) {
            material = new ArrayList<TRoadLanesLaneSectionLrLaneMaterial>();
        }
        return this.material;
    }

    /**
     * Gets the value of the visibility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the visibility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVisibility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadLanesLaneSectionLrLaneVisibility }
     * 
     * 
     */
    public List<TRoadLanesLaneSectionLrLaneVisibility> getVisibility() {
        if (visibility == null) {
            visibility = new ArrayList<TRoadLanesLaneSectionLrLaneVisibility>();
        }
        return this.visibility;
    }

    /**
     * Gets the value of the speed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the speed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpeed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadLanesLaneSectionLrLaneSpeed }
     * 
     * 
     */
    public List<TRoadLanesLaneSectionLrLaneSpeed> getSpeed() {
        if (speed == null) {
            speed = new ArrayList<TRoadLanesLaneSectionLrLaneSpeed>();
        }
        return this.speed;
    }

    /**
     * Gets the value of the access property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the access property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadLanesLaneSectionLrLaneAccess }
     * 
     * 
     */
    public List<TRoadLanesLaneSectionLrLaneAccess> getAccess() {
        if (access == null) {
            access = new ArrayList<TRoadLanesLaneSectionLrLaneAccess>();
        }
        return this.access;
    }

    /**
     * Gets the value of the height property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the height property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHeight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadLanesLaneSectionLrLaneHeight }
     * 
     * 
     */
    public List<TRoadLanesLaneSectionLrLaneHeight> getHeight() {
        if (height == null) {
            height = new ArrayList<TRoadLanesLaneSectionLrLaneHeight>();
        }
        return this.height;
    }

    /**
     * Gets the value of the rule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRoadLanesLaneSectionLrLaneRule }
     * 
     * 
     */
    public List<TRoadLanesLaneSectionLrLaneRule> getRule() {
        if (rule == null) {
            rule = new ArrayList<TRoadLanesLaneSectionLrLaneRule>();
        }
        return this.rule;
    }

    /**
     * Gets the value of the userData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TUserData }
     * 
     * 
     */
    public List<TUserData> getUserData() {
        if (userData == null) {
            userData = new ArrayList<TUserData>();
        }
        return this.userData;
    }

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInclude }
     * 
     * 
     */
    public List<TInclude> getInclude() {
        if (include == null) {
            include = new ArrayList<TInclude>();
        }
        return this.include;
    }

    /**
     * Gets the value of the dataQuality property.
     * 
     * @return
     *     possible object is
     *     {@link TDataQuality }
     *     
     */
    public TDataQuality getDataQuality() {
        return dataQuality;
    }

    /**
     * Sets the value of the dataQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataQuality }
     *     
     */
    public void setDataQuality(TDataQuality value) {
        this.dataQuality = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ELaneType }
     *     
     */
    public ELaneType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ELaneType }
     *     
     */
    public void setType(ELaneType value) {
        this.type = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link TBool }
     *     
     */
    public TBool getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link TBool }
     *     
     */
    public void setLevel(TBool value) {
        this.level = value;
    }

}
