//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.08 at 08:54:08 PM CEST 
//


package eu.opends.opendrive.data;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_road_planView_geometry_paramPoly3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_road_planView_geometry_paramPoly3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{}g_additionalData"/>
 *       &lt;attribute name="aU" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="bU" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="cU" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="dU" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="aV" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="bV" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="cV" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="dV" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="pRange" use="required" type="{}e_paramPoly3_pRange" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_road_planView_geometry_paramPoly3", propOrder = {
    "userData",
    "include",
    "dataQuality"
})
public class TRoadPlanViewGeometryParamPoly3 {

    protected List<TUserData> userData;
    protected List<TInclude> include;
    protected TDataQuality dataQuality;
    @XmlAttribute(name = "aU", required = true)
    protected double au;
    @XmlAttribute(name = "bU", required = true)
    protected double bu;
    @XmlAttribute(name = "cU", required = true)
    protected double cu;
    @XmlAttribute(name = "dU", required = true)
    protected double du;
    @XmlAttribute(name = "aV", required = true)
    protected double av;
    @XmlAttribute(name = "bV", required = true)
    protected double bv;
    @XmlAttribute(name = "cV", required = true)
    protected double cv;
    @XmlAttribute(name = "dV", required = true)
    protected double dv;
    @XmlAttribute(name = "pRange", required = true)
    protected EParamPoly3PRange pRange;

    /**
     * Gets the value of the userData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TUserData }
     * 
     * 
     */
    public List<TUserData> getUserData() {
        if (userData == null) {
            userData = new ArrayList<TUserData>();
        }
        return this.userData;
    }

    /**
     * Gets the value of the include property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the include property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInclude().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TInclude }
     * 
     * 
     */
    public List<TInclude> getInclude() {
        if (include == null) {
            include = new ArrayList<TInclude>();
        }
        return this.include;
    }

    /**
     * Gets the value of the dataQuality property.
     * 
     * @return
     *     possible object is
     *     {@link TDataQuality }
     *     
     */
    public TDataQuality getDataQuality() {
        return dataQuality;
    }

    /**
     * Sets the value of the dataQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDataQuality }
     *     
     */
    public void setDataQuality(TDataQuality value) {
        this.dataQuality = value;
    }

    /**
     * Gets the value of the au property.
     * 
     */
    public double getAU() {
        return au;
    }

    /**
     * Sets the value of the au property.
     * 
     */
    public void setAU(double value) {
        this.au = value;
    }

    /**
     * Gets the value of the bu property.
     * 
     */
    public double getBU() {
        return bu;
    }

    /**
     * Sets the value of the bu property.
     * 
     */
    public void setBU(double value) {
        this.bu = value;
    }

    /**
     * Gets the value of the cu property.
     * 
     */
    public double getCU() {
        return cu;
    }

    /**
     * Sets the value of the cu property.
     * 
     */
    public void setCU(double value) {
        this.cu = value;
    }

    /**
     * Gets the value of the du property.
     * 
     */
    public double getDU() {
        return du;
    }

    /**
     * Sets the value of the du property.
     * 
     */
    public void setDU(double value) {
        this.du = value;
    }

    /**
     * Gets the value of the av property.
     * 
     */
    public double getAV() {
        return av;
    }

    /**
     * Sets the value of the av property.
     * 
     */
    public void setAV(double value) {
        this.av = value;
    }

    /**
     * Gets the value of the bv property.
     * 
     */
    public double getBV() {
        return bv;
    }

    /**
     * Sets the value of the bv property.
     * 
     */
    public void setBV(double value) {
        this.bv = value;
    }

    /**
     * Gets the value of the cv property.
     * 
     */
    public double getCV() {
        return cv;
    }

    /**
     * Sets the value of the cv property.
     * 
     */
    public void setCV(double value) {
        this.cv = value;
    }

    /**
     * Gets the value of the dv property.
     * 
     */
    public double getDV() {
        return dv;
    }

    /**
     * Sets the value of the dv property.
     * 
     */
    public void setDV(double value) {
        this.dv = value;
    }

    /**
     * Gets the value of the pRange property.
     * 
     * @return
     *     possible object is
     *     {@link EParamPoly3PRange }
     *     
     */
    public EParamPoly3PRange getPRange() {
        return pRange;
    }

    /**
     * Sets the value of the pRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link EParamPoly3PRange }
     *     
     */
    public void setPRange(EParamPoly3PRange value) {
        this.pRange = value;
    }

}
