//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 03:20:44 PM CET 
//


package eu.opends.opendrive.roadGenerator;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.opends.opendrive.roadGenerator package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RoadDescription_QNAME = new QName("http://opends.eu/roadDescription", "roadDescription");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.opends.opendrive.roadGenerator
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoadDescriptionType }
     * 
     */
    public RoadDescriptionType createRoadDescriptionType() {
        return new RoadDescriptionType();
    }

    /**
     * Create an instance of {@link OnroadPositionType }
     * 
     */
    public OnroadPositionType createOnroadPositionType() {
        return new OnroadPositionType();
    }

    /**
     * Create an instance of {@link IntersectionType }
     * 
     */
    public IntersectionType createIntersectionType() {
        return new IntersectionType();
    }

    /**
     * Create an instance of {@link PreferredConnectionsType }
     * 
     */
    public PreferredConnectionsType createPreferredConnectionsType() {
        return new PreferredConnectionsType();
    }

    /**
     * Create an instance of {@link TerminateSimulationType }
     * 
     */
    public TerminateSimulationType createTerminateSimulationType() {
        return new TerminateSimulationType();
    }

    /**
     * Create an instance of {@link ConnectionType }
     * 
     */
    public ConnectionType createConnectionType() {
        return new ConnectionType();
    }

    /**
     * Create an instance of {@link IncomingSegmentType }
     * 
     */
    public IncomingSegmentType createIncomingSegmentType() {
        return new IncomingSegmentType();
    }

    /**
     * Create an instance of {@link SegmentsType }
     * 
     */
    public SegmentsType createSegmentsType() {
        return new SegmentsType();
    }

    /**
     * Create an instance of {@link SuccessorType }
     * 
     */
    public SuccessorType createSuccessorType() {
        return new SuccessorType();
    }

    /**
     * Create an instance of {@link SuccessorIntersectionType }
     * 
     */
    public SuccessorIntersectionType createSuccessorIntersectionType() {
        return new SuccessorIntersectionType();
    }

    /**
     * Create an instance of {@link IntersectionsType }
     * 
     */
    public IntersectionsType createIntersectionsType() {
        return new IntersectionsType();
    }

    /**
     * Create an instance of {@link HeightMapType }
     * 
     */
    public HeightMapType createHeightMapType() {
        return new HeightMapType();
    }

    /**
     * Create an instance of {@link TargetsType }
     * 
     */
    public TargetsType createTargetsType() {
        return new TargetsType();
    }

    /**
     * Create an instance of {@link PedestrianType }
     * 
     */
    public PedestrianType createPedestrianType() {
        return new PedestrianType();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link OffroadPositionType }
     * 
     */
    public OffroadPositionType createOffroadPositionType() {
        return new OffroadPositionType();
    }

    /**
     * Create an instance of {@link LaneLayoutType }
     * 
     */
    public LaneLayoutType createLaneLayoutType() {
        return new LaneLayoutType();
    }

    /**
     * Create an instance of {@link SurfaceType }
     * 
     */
    public SurfaceType createSurfaceType() {
        return new SurfaceType();
    }

    /**
     * Create an instance of {@link CodriverType }
     * 
     */
    public CodriverType createCodriverType() {
        return new CodriverType();
    }

    /**
     * Create an instance of {@link TrafficType }
     * 
     */
    public TrafficType createTrafficType() {
        return new TrafficType();
    }

    /**
     * Create an instance of {@link TargetType }
     * 
     */
    public TargetType createTargetType() {
        return new TargetType();
    }

    /**
     * Create an instance of {@link RoadStartingPointType }
     * 
     */
    public RoadStartingPointType createRoadStartingPointType() {
        return new RoadStartingPointType();
    }

    /**
     * Create an instance of {@link VehiclesType }
     * 
     */
    public VehiclesType createVehiclesType() {
        return new VehiclesType();
    }

    /**
     * Create an instance of {@link ExtentType }
     * 
     */
    public ExtentType createExtentType() {
        return new ExtentType();
    }

    /**
     * Create an instance of {@link GeometriesType }
     * 
     */
    public GeometriesType createGeometriesType() {
        return new GeometriesType();
    }

    /**
     * Create an instance of {@link SuccessorSegmentType }
     * 
     */
    public SuccessorSegmentType createSuccessorSegmentType() {
        return new SuccessorSegmentType();
    }

    /**
     * Create an instance of {@link OutgoingSegmentType }
     * 
     */
    public OutgoingSegmentType createOutgoingSegmentType() {
        return new OutgoingSegmentType();
    }

    /**
     * Create an instance of {@link TerrainType }
     * 
     */
    public TerrainType createTerrainType() {
        return new TerrainType();
    }

    /**
     * Create an instance of {@link PedestriansType }
     * 
     */
    public PedestriansType createPedestriansType() {
        return new PedestriansType();
    }

    /**
     * Create an instance of {@link SegmentType }
     * 
     */
    public SegmentType createSegmentType() {
        return new SegmentType();
    }

    /**
     * Create an instance of {@link GeometryType }
     * 
     */
    public GeometryType createGeometryType() {
        return new GeometryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://opends.eu/roadDescription", name = "roadDescription")
    public JAXBElement<RoadDescriptionType> createRoadDescription(RoadDescriptionType value) {
        return new JAXBElement<RoadDescriptionType>(_RoadDescription_QNAME, RoadDescriptionType.class, null, value);
    }

}
