//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 03:20:44 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://opends.eu/roadDescription", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package eu.opends.opendrive.roadGenerator;
