//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 03:20:44 PM CET 
//


package eu.opends.opendrive.roadGenerator;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for segmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="segmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="geometries" type="{http://opends.eu/roadDescription}geometriesType"/>
 *         &lt;element name="laneLayout" type="{http://opends.eu/roadDescription}laneLayoutType" minOccurs="0"/>
 *         &lt;element name="surface" type="{http://opends.eu/roadDescription}surfaceType" minOccurs="0"/>
 *         &lt;element name="successor" type="{http://opends.eu/roadDescription}successorType" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="initial" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "segmentType", propOrder = {

})
public class SegmentType {

    @XmlElement(required = true)
    protected GeometriesType geometries;
    protected LaneLayoutType laneLayout;
    protected SurfaceType surface;
    protected SuccessorType successor;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "initial")
    protected Boolean initial;

    /**
     * Gets the value of the geometries property.
     * 
     * @return
     *     possible object is
     *     {@link GeometriesType }
     *     
     */
    public GeometriesType getGeometries() {
        return geometries;
    }

    /**
     * Sets the value of the geometries property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeometriesType }
     *     
     */
    public void setGeometries(GeometriesType value) {
        this.geometries = value;
    }

    /**
     * Gets the value of the laneLayout property.
     * 
     * @return
     *     possible object is
     *     {@link LaneLayoutType }
     *     
     */
    public LaneLayoutType getLaneLayout() {
        return laneLayout;
    }

    /**
     * Sets the value of the laneLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link LaneLayoutType }
     *     
     */
    public void setLaneLayout(LaneLayoutType value) {
        this.laneLayout = value;
    }

    /**
     * Gets the value of the surface property.
     * 
     * @return
     *     possible object is
     *     {@link SurfaceType }
     *     
     */
    public SurfaceType getSurface() {
        return surface;
    }

    /**
     * Sets the value of the surface property.
     * 
     * @param value
     *     allowed object is
     *     {@link SurfaceType }
     *     
     */
    public void setSurface(SurfaceType value) {
        this.surface = value;
    }

    /**
     * Gets the value of the successor property.
     * 
     * @return
     *     possible object is
     *     {@link SuccessorType }
     *     
     */
    public SuccessorType getSuccessor() {
        return successor;
    }

    /**
     * Sets the value of the successor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuccessorType }
     *     
     */
    public void setSuccessor(SuccessorType value) {
        this.successor = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the initial property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInitial() {
        return initial;
    }

    /**
     * Sets the value of the initial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInitial(Boolean value) {
        this.initial = value;
    }

}
