//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 03:20:44 PM CET 
//


package eu.opends.opendrive.roadGenerator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for successorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="successorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="segment" type="{http://opends.eu/roadDescription}successorSegmentType"/>
 *         &lt;element name="intersection" type="{http://opends.eu/roadDescription}successorIntersectionType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "successorType", propOrder = {
    "segment",
    "intersection"
})
public class SuccessorType {

    protected SuccessorSegmentType segment;
    protected SuccessorIntersectionType intersection;

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link SuccessorSegmentType }
     *     
     */
    public SuccessorSegmentType getSegment() {
        return segment;
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuccessorSegmentType }
     *     
     */
    public void setSegment(SuccessorSegmentType value) {
        this.segment = value;
    }

    /**
     * Gets the value of the intersection property.
     * 
     * @return
     *     possible object is
     *     {@link SuccessorIntersectionType }
     *     
     */
    public SuccessorIntersectionType getIntersection() {
        return intersection;
    }

    /**
     * Sets the value of the intersection property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuccessorIntersectionType }
     *     
     */
    public void setIntersection(SuccessorIntersectionType value) {
        this.intersection = value;
    }

}
