//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 03:20:44 PM CET 
//


package eu.opends.opendrive.roadGenerator;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for terminateSimulationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="terminateSimulationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="onTargetPositionReached" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="onRoadEndReached" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "terminateSimulationType")
public class TerminateSimulationType {

    @XmlAttribute(name = "onTargetPositionReached")
    protected Boolean onTargetPositionReached;
    @XmlAttribute(name = "onRoadEndReached")
    protected Boolean onRoadEndReached;

    /**
     * Gets the value of the onTargetPositionReached property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnTargetPositionReached() {
        return onTargetPositionReached;
    }

    /**
     * Sets the value of the onTargetPositionReached property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnTargetPositionReached(Boolean value) {
        this.onTargetPositionReached = value;
    }

    /**
     * Gets the value of the onRoadEndReached property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnRoadEndReached() {
        return onRoadEndReached;
    }

    /**
     * Sets the value of the onRoadEndReached property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnRoadEndReached(Boolean value) {
        this.onRoadEndReached = value;
    }

}
