//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 03:20:44 PM CET 
//


package eu.opends.opendrive.roadGenerator;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for terrainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="terrainType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="extent" type="{http://opends.eu/roadDescription}extentType"/>
 *         &lt;element name="heightMap" type="{http://opends.eu/roadDescription}heightMapType"/>
 *         &lt;element name="roadStartingPoint" type="{http://opends.eu/roadDescription}roadStartingPointType"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "terrainType", propOrder = {

})
public class TerrainType {

    @XmlElement(required = true)
    protected ExtentType extent;
    @XmlElement(required = true)
    protected HeightMapType heightMap;
    @XmlElement(required = true)
    protected RoadStartingPointType roadStartingPoint;

    /**
     * Gets the value of the extent property.
     * 
     * @return
     *     possible object is
     *     {@link ExtentType }
     *     
     */
    public ExtentType getExtent() {
        return extent;
    }

    /**
     * Sets the value of the extent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtentType }
     *     
     */
    public void setExtent(ExtentType value) {
        this.extent = value;
    }

    /**
     * Gets the value of the heightMap property.
     * 
     * @return
     *     possible object is
     *     {@link HeightMapType }
     *     
     */
    public HeightMapType getHeightMap() {
        return heightMap;
    }

    /**
     * Sets the value of the heightMap property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeightMapType }
     *     
     */
    public void setHeightMap(HeightMapType value) {
        this.heightMap = value;
    }

    /**
     * Gets the value of the roadStartingPoint property.
     * 
     * @return
     *     possible object is
     *     {@link RoadStartingPointType }
     *     
     */
    public RoadStartingPointType getRoadStartingPoint() {
        return roadStartingPoint;
    }

    /**
     * Sets the value of the roadStartingPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadStartingPointType }
     *     
     */
    public void setRoadStartingPoint(RoadStartingPointType value) {
        this.roadStartingPoint = value;
    }

}
